name: Deploy React to S3

on:
  push:
    branches: [ "dev" ]
    paths:
      - "frontend/**"
  pull_request:
    branches: [ "dev" ]
    paths:
      - "frontend/**"

env:
  AWS_REGION: ap-northeast-2  # AWS 리전 설정
  AWS_S3_BUCKET: bangbang-check

permissions:
  id-token: write      # OIDC 토큰을 가져올 수 있도록 허용
  contents: read  # 코드 읽기 권한만 부여

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # GitHub 저장소에서 코드를 체크아웃(다운로드)
      - uses: actions/checkout@v3 

      # Node.js 버전 18을 설정
      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # frontend 디렉토리에서 프로젝트의 종속성 설치
      - name: install deps
        run: npm install ajv@^6.12.6 --save --legacy-peer-deps 
        working-directory: ./frontend

      # 리액트 빌드 및 export
      - name: Build and Export
        run: |
          npm run build
        working-directory: ./frontend

    # AWS 자격 증명 설정 (깃허브 OIDC 사용)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::418295688903:role/GitHubActionsOIDCRole 
          role-session-name: GitHub_to_AWS_via_FederatedOIDC 
          aws-region: ${{ env.AWS_REGION }}

      # AWS CLI로 S3에 업로드
      - name: Upload to S3 using AWS CLI
        run: |
          aws s3 sync ./frontend/build s3://${{ env.AWS_S3_BUCKET }} --delete
