name: Deploy Lambda & Terraform

on:
  push:
    branches: [ "feat/17/projects_room_crud" ] # 현재 브랜치
    paths:
      - "backend/**"
      - "infra/**"
  pull_request:
    branches: [ "dev" ]
    paths:
      - "backend/**"
      - "infra/**"
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2  # AWS 리전 설정
  AWS_S3_BUCKET: lambda-upload-bangbang-check-bucket

permissions:
  id-token: write      # OIDC 토큰을 가져올 수 있도록 허용
  contents: write  # 코드 읽기 권한만 부여

jobs:
  lambda_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # 바뀐파일 비교를 위해 fetch
    - name: Fetch dev branch
      run: git fetch origin dev

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Run tests 
      run: |
        if [ -f backend/lambda_tests/runAllTests.js ]; then
          echo "Running tests for changed Lambda functions"
          cd backend
          npm install
          cd lambda_tests
          npm test
        else
          echo "No runAllTests.js found, skipping tests."
        fi

    - name: Detect changed Lambda function folders
      id: detect
      run: |
        changed_dirs=$(git diff --name-only origin/dev...HEAD | grep '^backend/lambda_functions/' | awk -F'/' '{print $3}' | sort -u | uniq | tr '\n' ' ')
        echo "CHANGED_DIRS=$changed_dirs" >> $GITHUB_ENV

        changed_layers=$(git diff --name-only origin/dev...HEAD | grep '^backend/lambda_layer/' | awk -F'/' '{print $3}' | sort -u | uniq | tr '\n' ' ')
        echo "CHANGED_LAYERS=$changed_layers" >> $GITHUB_ENV

    - name: npm install changed functions
      run: |
        for dir in $CHANGED_DIRS; do
          if [ -d "$dir" ] && [ -f "$dir/package.json" ]; then
            echo "Installing dependencies for $dir"
            cd backend/lambda_functions/$dir
            cd $dir
            npm install
            cd -
          fi
        done

    # AWS 자격 증명 설정 (깃허브 OIDC 사용)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::418295688903:role/GitHubActionsOIDCRole 
        role-session-name: GitHub_to_AWS_via_FederatedOIDC 
        aws-region: ${{ env.AWS_REGION }}

    - name: Zip lambda layers and upload to S3
      run: |
        for layer in $CHANGED_LAYERS; do
          if [ -d "backend/lambda_layer/$layer" ]; then
            cd backend/lambda_layer/$layer/nodejs
            npm install
            cd ..
            echo "Zipping changed layer $layer"
            zip -r /tmp/${layer}.zip nodejs
            aws s3 cp /tmp/${layer}.zip s3://${{ env.AWS_S3_BUCKET }}/lambda_layer/${layer}.zip
          fi
        done

    - name: Update Lambda Layers
      run: |
        for layer in $CHANGED_LAYERS; do
          if [ ! -z "$layer" ]; then
            exists=$(aws lambda list-layer-versions --layer-name $layer --query 'LayerVersions | length(@)' --output text 2>/dev/null || echo 0)
            if [ "$exists" -gt 0 ]; then
              echo "Publishing new version of existing layer $layer"
              aws lambda publish-layer-version \
                --layer-name $layer \
                --content S3Bucket=${{ env.AWS_S3_BUCKET }},S3Key=lambda_layer/${layer}.zip \
                --compatible-runtimes nodejs20.x
            else
              echo "Layer $layer does not exist, skipping publish."
            fi
          fi
        done

    - name: Zip and upload to S3
      run: |
        for dir in $CHANGED_DIRS; do
          echo "Zipping and uploading $dir"
          cd backend/lambda_functions/$dir
          zip -r /tmp/$dir.zip . -x "*.md" "*.zip"
          aws s3 cp /tmp/$dir.zip s3://${{ env.AWS_S3_BUCKET }}/$dir.zip
          cd -
        done
    
    - name: Update Lambda function code
      run: |
        for dir in $CHANGED_DIRS; do
          if aws lambda get-function --function-name "$dir" > /dev/null 2>&1; then
            echo "Updating Lambda function code for $dir"
            aws lambda update-function-code --function-name "$dir" --s3-bucket ${{ env.AWS_S3_BUCKET }} --s3-key "$dir.zip"
          else
            echo "Lambda function $dir does not exist, skipping update."
          fi  
        done

  terraform:
    uses: ./.github/workflows/terraform.yml
    needs: lambda_upload
